services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ChamberOrchestra\FormBundle\:
    resource: '../../'
    exclude: "../../{DependencyInjection,Resources,Exception}"

  ChamberOrchestra\FormBundle\Serializer\Normalizer\ProblemNormalizer:
    arguments:
      $debug: '%kernel.debug%'

  ChamberOrchestra\FormBundle\Extension\TelExtension:
    tags:
      - { name: form.type_extension }